const routes = require("express").Router()
const controlProduct = require("../controllers/Product")
const authentication = require("../middlewares/authentication")
const { toEditDeleteProduct, forAdmin } = require("../middlewares/authorization")
const upload = require("../middlewares/awsUpload")

routes.get("/", controlProduct.getAllProducts)
routes.post("/", authentication, upload.single("image_url"), controlProduct.postProduct)
routes.get("/mine", authentication, controlProduct.myProducts)
routes.put("/:idProduct", authentication, upload.single("image_url"), toEditDeleteProduct, controlProduct.editProduct)
routes.put("/normal/:idProduct", authentication, toEditDeleteProduct, controlProduct.editProduct)
routes.delete("/:idProduct", authentication, toEditDeleteProduct, controlProduct.deleteProduct)
routes.get("/:idProduct", controlProduct.getDetailById)
routes.get("/category/:category", controlProduct.getProductsByCategory)
routes.get("/official/byOfficial", authentication, controlProduct.getProductsByOfficialStore)
module.exports = routes